### ISSUE TITLE
Cannot control Duette (6) via ESPHome bluetooth proxy

### ISSUE THREAD

**Issue by cloom** [patman15/hdpv_ble#5]
### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issue](https://github.com/patman15/hdpv_ble/issues?q=is%3Aissue+label%3A%22Bug%22+).

### Describe the issue

Hello,

I might not have done things in order (see reproduction steps) but I should have the proper HOME_KEY setup in the const.py file of the custom_component.

I can see the status of the blinds I have added to the component: opening, closing, open, close, percentage of opening, battery level.

I cannot control the blinds, I get the following error when I try to open, close, stop:
```
Failed to perform the action cover/stop_cover. Device did not send confirmation.
```

I have enabled the logs, restarted HA, tried to control a blind, waiting for the error and stopped the logs.

Let me know if there is anything I can do to test.

### Reproduction steps

1. Configure blinds normally (with the app on the phone)
2. Add a remote (optional but in case this has an impact)
3. Install an ESPHome Bluetooth Proxy in HA
4. Install the hdpv_ble custom component
5. Reboot HA
6. Add blinds to the component and verify you can see the status of the blinds
7. Get the HOME_KEY using [Waydroid](https://waydro.id/)
8. Convert the HOME_KEY into the python byte format and add it to the [const.py file](https://github.com/patman15/hdpv_ble/blob/main/custom_components/hunterdouglas_powerview_ble/const.py#L23)
9. Restart HA
10. Test any command: open, close, stop.

### Debug logs

```text
2024-12-30 11:34:38.330 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hunterdouglas_powerview_ble which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 11:34:38.333 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 11:34:38.337 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration frigate which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 11:34:38.339 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration sonoff which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 11:34:38.342 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration dlight which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2024-12-30 11:34:55.417 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.cold_water_daily (<class 'homeassistant.components.utility_meter.sensor.UtilityMeterSensor'>) is using native unit of measurement 'm3' which is not a valid unit for the device class ('water') it is using; expected one of ['m³', 'CCF', 'gal', 'ft³', 'L']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+utility_meter%22
2024-12-30 11:34:55.434 WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.hot_water_daily (<class 'homeassistant.components.utility_meter.sensor.UtilityMeterSensor'>) is using native unit of measurement 'm3' which is not a valid unit for the device class ('water') it is using; expected one of ['m³', 'CCF', 'gal', 'ft³', 'L']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+utility_meter%22
2024-12-30 11:34:55.947 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Setup of <ConfigEntry entry_id=01JG9SMNNAGXESNZCK1HXANKBR version=1 domain=hunterdouglas_powerview_ble title=DUT:DDB8 state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=F9:4F:22:3F:6B:D5>
2024-12-30 11:34:55.948 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Initializing coordinator for DUT:DDB8 (F9:4F:22:3F:6B:D5)
2024-12-30 11:34:55.949 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8: querying device info
2024-12-30 11:34:55.949 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Connecting DUT:DDB8
2024-12-30 11:34:55.950 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Setup of <ConfigEntry entry_id=01JG9SY03783Q865PW4SK8TP9V version=1 domain=hunterdouglas_powerview_ble title=DUT:5CDB state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=E7:B3:D2:48:EA:AB>
2024-12-30 11:34:55.950 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Initializing coordinator for DUT:5CDB (E7:B3:D2:48:EA:AB)
2024-12-30 11:34:55.951 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB: querying device info
2024-12-30 11:34:55.951 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Connecting DUT:5CDB
2024-12-30 11:34:58.915 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for eink @ 192.168.86.21: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.86.21', port=6053))]: [Errno 113] Connect call failed ('192.168.86.21', 6053) (SocketAPIError)
2024-12-30 11:34:58.979 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for kitchen_worktop @ 192.168.86.86: Error connecting to [AddrInfo(family=<AddressFamily.AF_INET: 2>, type=<SocketKind.SOCK_STREAM: 1>, proto=6, sockaddr=IPv4Sockaddr(address='192.168.86.86', port=6053))]: [Errno 113] Connect call failed ('192.168.86.86', 6053) (SocketAPIError)
2024-12-30 11:35:01.129 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] 	connect took 5s
2024-12-30 11:35:01.132 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying manufacturer(2a29)
2024-12-30 11:35:01.282 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying model(2a24)
2024-12-30 11:35:01.415 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying serial_nr(2a25)
2024-12-30 11:35:01.707 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying hw_rev(2a27)
2024-12-30 11:35:01.905 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] 	connect took 5s
2024-12-30 11:35:01.906 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying manufacturer(2a29)
2024-12-30 11:35:01.911 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying fw_rev(2a26)
2024-12-30 11:35:02.012 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying sw_rev(2a28)
2024-12-30 11:35:02.113 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying model(2a24)
2024-12-30 11:35:02.205 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Disconnecting device DUT:DDB8
2024-12-30 11:35:02.256 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying serial_nr(2a25)
2024-12-30 11:35:02.311 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Disconnected from F9:4F:22:3F:6B:D5
2024-12-30 11:35:02.312 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8 device data: {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': 'DDB8B563D3E19342', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:02.353 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': 'DDB8B563D3E19342', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:02.355 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': 'DDB8B563D3E19342', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:02.356 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': 'DDB8B563D3E19342', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:02.361 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': 'DDB8B563D3E19342', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:02.363 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:DDB8: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': 'DDB8B563D3E19342', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:02.365 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] BLE event BluetoothChange.ADVERTISEMENT: {2073: b'\xfb\xd7\x06\xa0\x0f\x00\x00\x00\xe2'}
2024-12-30 11:35:02.365 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] data sample {'rssi': -69, 'current_position': 100.0, 'position2': 0, 'position3': 0, 'tilt': 0, 'home_id': 55291, 'type_id': 6, 'is_opening': False, 'is_closing': False, 'battery_charging': False, 'battery_level': 100, 'resetMode': False, 'resetClock': True}
2024-12-30 11:35:02.510 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying hw_rev(2a27)
2024-12-30 11:35:02.720 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying fw_rev(2a26)
2024-12-30 11:35:02.833 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] querying sw_rev(2a28)
2024-12-30 11:35:03.034 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Disconnecting device DUT:5CDB
2024-12-30 11:35:03.134 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Disconnected from E7:B3:D2:48:EA:AB
2024-12-30 11:35:03.134 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB device data: {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': '5CDBDE760B8E1908', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:03.135 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': '5CDBDE760B8E1908', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:03.137 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': '5CDBDE760B8E1908', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:03.138 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': '5CDBDE760B8E1908', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:03.144 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': '5CDBDE760B8E1908', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:03.146 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB: device_info, {'manufacturer': 'Hunter Douglas', 'model': '6', 'serial_nr': '5CDBDE760B8E1908', 'hw_rev': '171104', 'fw_rev': '30', 'sw_rev': '418'}
2024-12-30 11:35:03.147 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] BLE event BluetoothChange.ADVERTISEMENT: {2073: b'\xfb\xd7\x06\x08\x06\x00\x00\x00\xe2'}
2024-12-30 11:35:03.148 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] data sample {'rssi': -74, 'current_position': 38.6, 'position2': 0, 'position3': 0, 'tilt': 0, 'home_id': 55291, 'type_id': 6, 'is_opening': False, 'is_closing': False, 'battery_charging': False, 'battery_level': 100, 'resetMode': False, 'resetClock': True}
2024-12-30 11:35:03.221 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({%- set p_debut_machine = states('input_number.washing_machine_power_at_start') | round(2) -%} {%- set p_fin_machine = states('sensor.washing_machine_energy') | round(2) -%} {%- set p_cycle_machine = p_fin_machine - p_debut_machine -%} {{ (p_cycle_machine) | round(2) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1928, in forgiving_round
    value = round(float(value), precision)
                  ~~~~~^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 631, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2733, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1933, in forgiving_round
    raise_no_default("round", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1909, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: round got invalid input 'unknown' when rendering template '{%- set p_debut_machine = states('input_number.washing_machine_power_at_start') | round(2) -%} {%- set p_fin_machine = states('sensor.washing_machine_energy') | round(2) -%} {%- set p_cycle_machine = p_fin_machine - p_debut_machine -%} {{ (p_cycle_machine) | round(2) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: round got invalid input 'unknown' when rendering template '{%- set p_debut_machine = states('input_number.washing_machine_power_at_start') | round(2) -%} {%- set p_fin_machine = states('sensor.washing_machine_energy') | round(2) -%} {%- set p_cycle_machine = p_fin_machine - p_debut_machine -%} {{ (p_cycle_machine) | round(2) }}' but no default was specified
2024-12-30 11:35:03.235 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: round got invalid input 'unknown' when rendering template '{%- set p_debut_machine = states('input_number.washing_machine_power_at_start') | round(2) -%} {%- set p_fin_machine = states('sensor.washing_machine_energy') | round(2) -%} {%- set p_cycle_machine = p_fin_machine - p_debut_machine -%} {{ (p_cycle_machine) | round(2) }}' but no default was specified') while processing template 'Template<template=({%- set p_debut_machine = states('input_number.washing_machine_power_at_start') | round(2) -%} {%- set p_fin_machine = states('sensor.washing_machine_energy') | round(2) -%} {%- set p_cycle_machine = p_fin_machine - p_debut_machine -%} {{ (p_cycle_machine) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.washing_machine_last_energy'
2024-12-30 11:35:03.241 ERROR (MainThread) [homeassistant.helpers.event] Error while processing template: Template<template=({%- set p_debut_dish = states('input_number.dishwasher_power_at_start') | round(2) -%} {%- set p_fin_dish = states('sensor.dishwasher_energy') | round(2) -%} {%- set p_cycle_dish = p_fin_dish - p_debut_dish -%} {{ (p_cycle_dish) | round(2) }}) renders=2>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1928, in forgiving_round
    value = round(float(value), precision)
                  ~~~~~^^^^^^^
ValueError: could not convert string to float: 'unknown'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 631, in async_render
    render_result = _render_with_context(self.template, compiled, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 2733, in _render_with_context
    return template.render(**kwargs)
           ~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 1304, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.13/site-packages/jinja2/environment.py", line 939, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 1, in top-level template code
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1933, in forgiving_round
    raise_no_default("round", value)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 1909, in raise_no_default
    raise ValueError(
    ...<2 lines>...
    )
ValueError: Template error: round got invalid input 'unknown' when rendering template '{%- set p_debut_dish = states('input_number.dishwasher_power_at_start') | round(2) -%} {%- set p_fin_dish = states('sensor.dishwasher_energy') | round(2) -%} {%- set p_cycle_dish = p_fin_dish - p_debut_dish -%} {{ (p_cycle_dish) | round(2) }}' but no default was specified

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 748, in async_render_to_info
    render_info._result = self.async_render(  # noqa: SLF001
                          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
        variables, strict=strict, log_fn=log_fn, **kwargs
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 633, in async_render
    raise TemplateError(err) from err
homeassistant.exceptions.TemplateError: ValueError: Template error: round got invalid input 'unknown' when rendering template '{%- set p_debut_dish = states('input_number.dishwasher_power_at_start') | round(2) -%} {%- set p_fin_dish = states('sensor.dishwasher_energy') | round(2) -%} {%- set p_cycle_dish = p_fin_dish - p_debut_dish -%} {{ (p_cycle_dish) | round(2) }}' but no default was specified
2024-12-30 11:35:03.250 ERROR (MainThread) [homeassistant.components.template.template_entity] TemplateError('ValueError: Template error: round got invalid input 'unknown' when rendering template '{%- set p_debut_dish = states('input_number.dishwasher_power_at_start') | round(2) -%} {%- set p_fin_dish = states('sensor.dishwasher_energy') | round(2) -%} {%- set p_cycle_dish = p_fin_dish - p_debut_dish -%} {{ (p_cycle_dish) | round(2) }}' but no default was specified') while processing template 'Template<template=({%- set p_debut_dish = states('input_number.dishwasher_power_at_start') | round(2) -%} {%- set p_fin_dish = states('sensor.dishwasher_energy') | round(2) -%} {%- set p_cycle_dish = p_fin_dish - p_debut_dish -%} {{ (p_cycle_dish) | round(2) }}) renders=4>' for attribute '_attr_native_value' in entity 'sensor.dishwasher_last_energy'
2024-12-30 11:35:08.285 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:35:14.104 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:35:21.044 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:35:26.734 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:35:35.326 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:35:48.200 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:36:07.407 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:36:28.656 ERROR (MainThread) [homeassistant.components.telegram_bot.polling] Conflict: Conflict: terminated by other getUpdates request; make sure that only one bot instance is running
2024-12-30 11:36:33.410 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] close cover
2024-12-30 11:36:33.410 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB close
2024-12-30 11:36:33.410 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] DUT:5CDB setting position to 0
2024-12-30 11:36:33.411 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Connecting DUT:5CDB
2024-12-30 11:36:34.592 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] 	connect took 1s
2024-12-30 11:36:34.595 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] sending cmd: b'WD\xe9]\xe5FKa/\xe7\xae\xa0\xa8'
2024-12-30 11:36:34.600 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] waiting for response
2024-12-30 11:36:35.185 DEBUG (MainThread) [custom_components.hunterdouglas_powerview_ble] Disconnected from E7:B3:D2:48:EA:AB
2024-12-30 11:36:39.602 ERROR (MainThread) [custom_components.hunterdouglas_powerview_ble] Error: TimeoutError - Device did not send confirmation.
2024-12-30 11:36:39.603 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140030495755712] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "/config/custom_components/hunterdouglas_powerview_ble/api.py", line 106, in _wait_event
    await self._data_event.wait()
  File "/usr/local/lib/python3.13/asyncio/locks.py", line 213, in wait
    await fut
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hunterdouglas_powerview_ble/api.py", line 157, in _cmd
    await asyncio.wait_for(self._wait_event(), timeout=TIMEOUT)
  File "/usr/local/lib/python3.13/asyncio/tasks.py", line 506, in wait_for
    async with timeouts.timeout(timeout):
               ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/local/lib/python3.13/asyncio/timeouts.py", line 116, in __aexit__
    raise TimeoutError from exc_val
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/hunterdouglas_powerview_ble/cover.py", line 158, in async_close_cover
    await self._coord.api.close()
  File "/config/custom_components/hunterdouglas_powerview_ble/api.py", line 219, in close
    await self.set_position(CLOSED_POSITION, disconnect=False)
  File "/config/custom_components/hunterdouglas_powerview_ble/api.py", line 195, in set_position
    await self._cmd(
    ...<8 lines>...
    )
  File "/config/custom_components/hunterdouglas_powerview_ble/api.py", line 160, in _cmd
    raise TimeoutError("Device did not send confirmation.") from ex
TimeoutError: Device did not send confirmation.
```

**Comment by patman15** [comment]
Hmm, did the shade move? If not, the most likely reason in this case is that you entered a wrong key. You could try by removing the shade from the app, then restart the integration, then try to control again, if that does not work, I need to add more debugging / ask you for more input. :sunglasses:

**Comment by cloom** [comment]
> you entered a wrong key

You know the guy who wants to ask a question and put his key in a forum but changes couple of characters first... then tries to fix his issues before asking and end up copying the wrong key in the const.py file? Well... that's me :smile_cat: 

It works now!! Thank you so much for your hard work.

Feel free to poke me if you need a beta tester, maybe not a good one if I make silly mistakes like this :smile:

**Comment by patman15** [comment]
> It works now!! Thank you so much for your hard work.

Cool! Good to hear you succeeded!
Appreciate the feedback, the HD guys did not make it easy to implement the integration. :sunglasses: 

> Feel free to poke me if you need a beta tester, maybe not a good one if I make silly mistakes like this 😄

Thanks, will do so, when I have the next bigger step ready. But I also need to get a bit to the outside, enjoying the nice weather. :wink:
